# Generated by Django 5.0.7 on 2024-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="заголовок")),
                ("slug", models.CharField(max_length=150, verbose_name="slug")),
                ("content", models.TextField(verbose_name="содержимое")),
                (
                    "blog_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_preview/",
                        verbose_name="превью записи блога",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="признак публикации"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="кол-во просмотров"
                    ),
                ),
            ],
        ),
    ]
