# Generated by Django 5.0.7 on 2024-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="preview/",
                verbose_name="превью записи блога",
            ),
        ),
    ]
