# Generated by Django 4.2.2 on 2024-09-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_blog_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "permissions": [
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_content", "Can edit content"),
                    ("can_edit_is_published", "Can edit is_published"),
                ],
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
