# Generated by Django 5.0.7 on 2024-08-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
